// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0cjpW_sPg5zFTkSg7vJMPUL_aBHTxLqY',
    appId: '1:1040857037801:android:0d8881ab0c07e8cde1e978',
    messagingSenderId: '1040857037801',
    projectId: 'fir-1-672e9',
    databaseURL: 'https://fir-1-672e9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-1-672e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6TG15t4MzYuqb3F2phYgNedGWeEnQ-Iw',
    appId: '1:1040857037801:ios:155aec99d5aa7b6ee1e978',
    messagingSenderId: '1040857037801',
    projectId: 'fir-1-672e9',
    databaseURL: 'https://fir-1-672e9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-1-672e9.appspot.com',
    iosBundleId: 'com.example.firebase1',
  );
}
