// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdXTjn06_l_3a-5cLSJg2Pu5uGNLhIAMU',
    appId: '1:632777005645:android:17a4ea30b663904cd49a04',
    messagingSenderId: '632777005645',
    projectId: 'todolist-b53e8',
    databaseURL: 'https://todolist-b53e8-default-rtdb.firebaseio.com',
    storageBucket: 'todolist-b53e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbCf7Ucue3oI3XJ-uiEkx8FJ9iSxjrlnY',
    appId: '1:632777005645:ios:ad86b4d91483d9ddd49a04',
    messagingSenderId: '632777005645',
    projectId: 'todolist-b53e8',
    databaseURL: 'https://todolist-b53e8-default-rtdb.firebaseio.com',
    storageBucket: 'todolist-b53e8.appspot.com',
    androidClientId: '632777005645-2db9nr4ab97sb1fcq7lqv7o1tdu5rha1.apps.googleusercontent.com',
    iosClientId: '632777005645-sjtgj7a2o4uttai9vdpnc60bna4qnthr.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase1',
  );
}
